### ISSUE TITLE
0.4.0: trying to use pytest-find-dependencies on setuptools

### ISSUE THREAD

**Issue by kloczek** [mrbean-bremen/pytest-find-dependencies#1]
I found that with `pytest-randomly` latest `setuptools` fails in random units.
So I've been trying to use `pytest-find-dependencies` on that module etst suiter and looks like pytest is failing with `INTERNALERROR`.
Here is the output:
```consile
+ PYTHONDONTWRITEBYTECODE=1
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-60.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ pytest -ra setuptools --pyargs setuptools.tests --find-dependencies
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/setuptools-60.1.0, configfile: pytest.ini
plugins: asyncio-0.16.0, tornado-0.8.1, forked-1.4.0, shutil-1.7.0, virtualenv-1.7.0, cov-3.0.0, flake8-1.0.7, xdist-2.5.0, checkdocs-2.7.1, find-dependencies-0.4.0
collected 979 items / 2 skipped / 977 selected
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/find_dependencies/plugin.py", line 35, in pytest_runtestloop
INTERNALERROR>     return run_tests(session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/find_dependencies/dependency_finder.py", line 119, in run_tests
INTERNALERROR>     items = [all_items[node_id] for node_id in node_ids]
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/find_dependencies/dependency_finder.py", line 119, in <listcomp>
INTERNALERROR>     items = [all_items[node_id] for node_id in node_ids]
INTERNALERROR> KeyError: 'dist.py::setuptools.dist.Distribution._expand_patterns'

2 skipped, 141 errors in 5.48s
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/find_dependencies/plugin.py", line 35, in pytest_runtestloop
INTERNALERROR>     return run_tests(session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/find_dependencies/dependency_finder.py", line 119, in run_tests
INTERNALERROR>     items = [all_items[node_id] for node_id in node_ids]
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/find_dependencies/dependency_finder.py", line 119, in <listcomp>
INTERNALERROR>     items = [all_items[node_id] for node_id in node_ids]
INTERNALERROR> KeyError: 'tests/test_windows_wrappers.py::TestGUI::test_basic'

2 skipped, 141 errors in 5.50s
```
May I ask for some help?

**Comment by mrbean-bremen** [comment]
Can you show how to reproduce this? How do I install setuptools for this?

**Comment by kloczek** [comment]
I'm using pep517 based build procedure. To uise it you need to have installrd `build` module than:
```console
git clone -b v60.1.0 https://github.com/pypa/setuptools
cd setuptools
python3 -sBm build -w
pytest -ra setuptools --pyargs setuptools.tests --find-dependencies
```

**Comment by mrbean-bremen** [comment]
I could not reproduce this. If I run this under Ubuntu, I actually get a test dependency:
```
Run dependency analysis for 584 tests.
Executed 1473 tests in 12 test runs.
Dependent tests:
  setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_transitive_extra_dependency depends on setuptools/tests/test_upload.py::TestUpload::test_upload_exception
```
but not a `pytest` error. I'm inclined to close this as I doubt that it is a problem with `pytest-dependencies` itself, but rather has to do with a very specific environment.
Given that this package is hardly used by anyone but myself, I don't think it is worth to spend more time in hunting it down.

**Comment by kloczek** [comment]
Hmm .. interesting.
Nay I ask which one version of the pytest you ware using?
In my case it is pytest 6.2.5.

**Comment by mrbean-bremen** [comment]
Also pytest 6.2.5.

**Comment by kloczek** [comment]
Hmm .. so what could be possible diffrence?🤔
What I can try to to do to diagnose that?

**Comment by mrbean-bremen** [comment]
FWIW, I added an additional check in the code to prevent that crash. I have no idea how that condition may happen, but you may have another try using the main branch version of pytest-find-dependencies.

**Comment by mrbean-bremen** [comment]
Made a patch release anyway, releases are cheap...

**Comment by kloczek** [comment]
OK will try to use new version :)
(just packaged it with deselected one unit in test suite which I've reported in new ticket)

**Comment by mrbean-bremen** [comment]
Did that work with setuptools, or didn't you get to it yet?

**Comment by kloczek** [comment]
Just tested 0.4.1 and lokks like it works now.

Closing
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-find-dependencies-0.4.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-find-dependencies-0.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-find-dependencies-0.4.1, configfile: setup.cfg, testpaths: tests
plugins: find-dependencies-0.4.1, mock-3.6.1, cov-3.0.0, hypothesis-6.32.1
collected 20 items

tests/test_find_dependencies.py ....................                                                                                                                 [100%]

=========================================================================== 20 passed in 16.74s ============================================================================
```

**Comment by kloczek** [comment]
I just realised that that bug still may b around.
In mean time I've switched to pep517 based build so I don't need anymore `setooptools` in build env.

**Comment by mrbean-bremen** [comment]
Well, you can always reopen the issue if you encounter this again, though I think this specific issue can't happen anymore.
